[theme.overrides]
info_fg = "#5e81ac" # dark blue
warning_fg = "#ebcb8b" # yellow
critical_fg = "#bf616a" # red

[icons]
icons = "awesome4"
# [icons.overrides]
# bat = ["|E|", "|_|", "|=|", "|F|"]
# bat_charging = "|^| "

[[block]]
block = "taskwarrior"
format = " $icon  $count tasks "
format_singular = " $icon  $count task "
format_everything_done = " nothing to do :)"
interval = 10
# [[block.filters]]
# name = "today"
# filter = "+PENDING +OVERDUE or +DUETODAY"
# [[block.filters]]
# name = "Hummingfab"
# filter = "project:Hummingfab +PENDING"


[[block]]
block = "temperature"
good = 40
idle = 50
warning = 80

[[block]]
block = "cpu"
format = " $icon  $utilization  $barchart "
interval = 1
merge_with_next = true

[[block]]
block="custom"
command = ''' sudo intel_gpu_top -l | head -n4 | tail -n1 | awk '{ print "GPU: " $9  "%" }' '''
interval = 1

[[block]]
block = "memory"
format = " $icon $mem_used.eng(prefix:M) /$mem_total($mem_used_percents.eng(w:2)) "
interval = 10
warning_mem = 70
critical_mem = 86

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid }" 
format_alt = " $icon {$graph_up}:{$ip}"
interval = 1

[[block]]
block = "time"
format = " $timestamp.datetime(f:'%a %d/%m %R') "
interval = 60
[[block.click]]
button = "right"
update = true
# format = " Kiev: $timestamp.datetime(f:'%R')"
# timezone = "Europe/Kiev"

[[block]]
block = "battery"
missing_format = "no battery?"
good = 80
info = 60
warning = 30

[[block]]
block = "docker"
interval = 5
format = " $icon $running /$total "

[[block]]
# block = "keyboard_layout"
# driver = "localebus"
# format = " $variant [$layout]"
block = "custom"
command = 'xkblayout-state print "%s"'
interval = 1

[[block]]
block = "sound"
driver = "pulseaudio"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "custom"
command = "echo \uf011" # assumes fontawesome icons
interval = "once"
[[block.click]]
button = "left"
cmd = "systemctl `echo -e 'poweroff\nreboot' | dmenu`"


