icons_format = "{icon}"

[icons]
icons = "awesome4"
[icons.overrides]
# bat = ["|E|", "|_|", "|=|", "|F|"]
# bat_charging = "|^| "

[[block]]
block = "taskwarrior"
interval = 60
format = " $icon count.eng(w:1) T"
format_singular = " $icon 1 T"
format_everything_done = ":)"
warning_threshold = 10
critical_threshold = 20
[[block.filters]]
name = "today"
filter = "+PENDING +OVERDUE or +DUETODAY"
[[block.filters]]
name = "Hummingfab"
filter = "project:Hummingfab +PENDING"


[[block]]
block = "watson"
show_time = true
state_path = "~/.config/watson/state"


[[block]]
block = "temperature"
merge_with_next = true

[[block]]
block = "cpu"
format = " $icon  $utilization  $barchart "
interval = 1
merge_with_next = true

[[block]]
block="custom"
command = ''' sudo intel_gpu_top -l | head -n4 | tail -n1 | awk '{ print "GPU: " $9  "%" }' '''
interval = 1

[[block]]
block = "memory"
format = " $icon $mem_used.eng(prefix:M)/$mem_total($mem_used_percents.eng(w:2)) "
interval = 10
warning_mem = 70
critical_mem = 90

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid }" 
interval = 1

[[block]]
block = "time"
format = " $timestamp.datetime(f:'%a %d/%m %R') "
interval = 60
[[block.click]]
button = "right"
update = true
# format = " Kiev: $timestamp.datetime(f:'%R')"
# timezone = "Europe/Kiev"

[[block]]
block = "docker"
interval = 5
format = " $icon $running/$total "

[[block]]
block = "keyboard_layout"
format = " $variant "
interval = 1
[block.mappings]
"us" = "US"
"ru" = "RU"

[[block]]
block = "sound"
driver = "pulseaudio"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "custom"
command = "echo \uf011" # assumes fontawesome icons
interval = "once"
[[block.click]]
button = "left"
cmd = "systemctl `echo -e 'poweroff\nreboot' | dmenu`"


